In [1]:
import numpy as np
np.__version__

'1.24.3'

In [14]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
a.shape
a.ndim


2

In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)
b.ndim
b.dtype

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


dtype('int32')

In [9]:
b = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
b.dtype

dtype('int64')