In [2]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
data_1d = np.array([1,2,3,4,5,6,7,8,9,0])
data_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
type(data_1d)

numpy.ndarray

In [8]:
data_2d = np.array([[1,2,3],[4,5,6]])
data_2d.ndim

2

In [9]:
reshaped_arr = data_2d.reshape(3,2)
reshaped_arr.ndim

2

In [11]:
data_2d[1,1]

5

In [17]:
data_1d[-2:-1]

array([9])

In [21]:
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
data_2d[0:,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
lst1 = [1,2,3]
lst2 = [4,5,6]
lst3 = lst1 + lst2
lst4 = [10]
lst5 = lst2 + lst4
lst5

[4, 5, 6, 10]

In [40]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
d = 10
e = b + d
e

array([14, 15, 16])

In [43]:
#Sum of all the elements in the np array
summ = np.sum(data_2d)
summ

21

In [44]:
col_sum = np.sum(data_2d, axis=0) # axis=0 means doing the operations by columnwise
col_sum

array([5, 7, 9])

In [1]:
row_mean = np.mean(data_2d, axis=1) # axis=1 means doing the operations by rowwise
row_mean

NameError: name 'np' is not defined

In [1]:
row_mean

NameError: name 'row_mean' is not defined

In [18]:
a = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,0,1]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [9, 0, 1]]])

In [19]:
a.ndim

3

In [20]:
a.shape

(2, 2, 3)

In [21]:
from numpy import *

In [46]:
b = array([1,2,3,4,5,6,7,8,9,0],dtype='int64')
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int64)

In [47]:
b.dtype

dtype('int64')

In [48]:
b.itemsize

8

In [49]:
b.size

10

In [50]:
b.nbytes # no.ofbytes * no.of elements in the array

80

In [54]:
c = array([[1,2,3],[4,5,6]])
c.nbytes

24

In [53]:
c.itemsize 

4

In [55]:
c.size # no.of elements present in the array.

6